include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/generated_plugin_registrant.dart'
  errors:
    invalid_annotation_target: ignore
