name: github_tracker
description: Tracking the top 100 GitHub software repos.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^1.0.4

  # Firebase
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1

  # Model definitions
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0 # Transitive dependency of freezed_annotation (added for transparency).

  # i18n
  intl: ^0.17.0

  # Platform utilities
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0

  # UI
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.1

  # Code generation (flutter pub run build_runner build)
  build_runner: ^2.1.11
  freezed: ^2.0.5
  json_serializable: ^6.2.0 # Transitive dependency of freezed (added for transparency).

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
