name: github_tracker
description: Tracking the top 100 GitHub software repos.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^0.14.0+3

  # Firebase
  cloud_firestore: ^2.2.1
  firebase_auth: ^1.3.0

  # Model definitions
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1 # Transitive dependency of freezed_annotation (added for transparency).

  # i18n
  intl: ^0.17.0

  # Platform utilities
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^1.0.3

  # Code generation (flutter pub run build_runner build)
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.0 # Transitive dependency of freezed (added for transparency).
