name: github_tracker
description: Tracking the top 100 GitHub software repos.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.0.2

  # Firebase
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3

  # Model definitions
  freezed_annotation: ^2.2.0
  json_annotation: ^4.6.0 # Transitive dependency of freezed_annotation (added for transparency).

  # i18n
  intl: ^0.17.0

  # Platform utilities
  url_launcher: ^6.1.6
  url_strategy: ^0.2.0

  # UI
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.1

  # Code generation (flutter pub run build_runner build)
  build_runner: ^2.3.2
  freezed: ^2.2.1

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
