name: github_tracker
description: Tracking the top 100 GitHub software repos.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^0.14.0

  # Model definitions
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1 # Transitive dependency of freezed_annotation (added for transparency).

  # Platform utilities
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  pedantic: ^1.11.0

  # Code generation
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0 # Transitive dependency of freezed (added for transparency).
