name: github_tracker
description: Tracking the top 100 GitHub software repos.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
