name: backend

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} linting
    strategy:
      matrix:
        package:
          - 'cloud_functions'
          - 'firestore'
      fail-fast: false
    env:
      working-directory: 'backend/${{ matrix.package }}'

    steps:
      - uses: actions/checkout@v2.5.0
      - run: npm install
        working-directory: ${{ env.working-directory }}
      - run: npm run lint
        working-directory: ${{ env.working-directory }}

  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} testing
    strategy:
      matrix:
        package:
          - 'firestore'
      fail-fast: false
    env:
      working-directory: 'backend/${{ matrix.package }}'

    steps:
      - uses: actions/checkout@v2.5.0
      - run: npm install
        working-directory: ${{ env.working-directory }}
      - run: npm test
        working-directory: ${{ env.working-directory }}
