name: frontend

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    timeout-minutes: 11
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} analysis on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
          - 'master'
        package:
          - 'github_tracker'
      fail-fast: false
    env:
      working-directory: 'frontend/${{ matrix.package }}'

    steps:
      - uses: actions/checkout@v2.4.2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: ${{ matrix.channel }}
      - name: pub get
        run: flutter pub get
        working-directory: ${{ env.working-directory }}
      - name: dart format
        run: dart format . --fix --set-exit-if-changed
        working-directory: ${{ env.working-directory }}
      - name: build_runner build
        run: flutter pub run build_runner build
        working-directory: ${{ env.working-directory }}
      - run: flutter analyze
        working-directory: ${{ env.working-directory }}

  test:
    timeout-minutes: 16
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} testing on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
          - 'master'
        package:
          - 'github_tracker'
      fail-fast: false
    env:
      working-directory: 'frontend/${{ matrix.package }}'

    steps:
      - uses: actions/checkout@v2.4.2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: ${{ matrix.channel }}
      - run: flutter pub get
        working-directory: ${{ env.working-directory }}
      - name: build_runner build
        run: flutter pub run build_runner build
        working-directory: ${{ env.working-directory }}
      - run: flutter test
        working-directory: ${{ env.working-directory }}
