name: frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/*/**'

jobs:
  analyze:
    timeout-minutes: 11
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} analysis on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
          - 'dev'
          - 'master'
        package:
          - 'github_tracker'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.5.1
        with:
          channel: ${{ matrix.channel }}
      - name: pub get
        run: flutter pub get
        working-directory: ${{ matrix.package }}
      - name: dart format
        working-directory: ${{ matrix.package }}
        run: dart format . --fix --set-exit-if-changed
      - run: flutter analyze
        working-directory: ${{ matrix.package }}

  test:
    timeout-minutes: 16
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} testing on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
          - 'dev'
          - 'master'
        package:
          - 'github_tracker'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.5.1
        with:
          channel: ${{ matrix.channel }}
      - run: flutter pub get
        working-directory: ${{ matrix.package }}
      - run: flutter test
        working-directory: ${{ matrix.package }}
