name: functions

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/functions.yml'
      - 'backend/functions/**'
      - 'backend/.firebaserc'
      - 'backend/firebase.json'

jobs:
  deploy:
    timeout-minutes: 5
    name: deployment
    runs-on: ubuntu-latest
    steps:
      # Make sure to cancel simultaneous workflow runs as functions deploy does not support deploying in parallel.
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.4.2
      - name: Install dependencies
        run: |
          cd backend/functions
          npm install --arch=x64
      - uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: backend
