name: Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    timeout-minutes: 9
    runs-on: ubuntu-latest
    name: github-tracker hosting preview
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          echo "todo: run pre-deploy scripts"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_TRACKER_B5C54 }}'
          projectId: github-tracker-b5c54
          entryPoint: backend
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
