name: Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: github-tracker hosting deploy
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          echo "todo: run pre-deploy scripts"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_TRACKER_B5C54 }}'
          channelId: live
          entryPoint: backend
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
