name: hosting

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/hosting.yml'
      - 'backend/.firebaserc'
      - 'backend/firebase.json'
      - 'frontend/github_tracker/**'

jobs:
  build_and_deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: deployment of github-tracker
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: 'true'
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'dev'
      - name: Build web app
        run: |
          cd frontend/github_tracker
          flutter pub get
          flutter pub run build_runner build
          flutter build web
      - name: Move frontend app to backend hosting
        run: |
          mkdir backend/public/
          mv frontend/github_tracker/build/web/* backend/public/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_TRACKER_B5C54 }}'
          channelId: live
          entryPoint: backend
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
